# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoc_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoc_msg.proto',
  package='protoc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10protoc_msg.proto\x12\x06protoc\",\n\x07\x42\x61seMsg\x12!\n\x08msg_type\x18\x01 \x01(\x0e\x32\x0f.protoc.MsgType\"*\n\x0cVehicle_Info\x12\x0b\n\x03vin\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\x08\"v\n\x0b\x43urrentPose\x12!\n\x08msg_type\x18\x01 \x01(\x0e\x32\x0f.protoc.MsgType\x12 \n\x03msg\x18\x02 \x01(\x0b\x32\x13.protoc.PoseStamped\x12\"\n\x04info\x18\x03 \x01(\x0b\x32\x14.protoc.Vehicle_Info\"/\n\nLidarVLP16\x12!\n\x08msg_type\x18\x01 \x01(\x0e\x32\x0f.protoc.MsgType\"I\n\x0bPoseStamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.protoc.Header\x12\x1a\n\x04pose\x18\x02 \x01(\x0b\x32\x0c.protoc.Pose\"D\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x1b\n\x05stamp\x18\x02 \x01(\x0b\x32\x0c.protoc.Time\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\"P\n\x04Pose\x12\x1f\n\x08position\x18\x01 \x01(\x0b\x32\r.protoc.Point\x12\'\n\x0borientation\x18\x02 \x01(\x0b\x32\x12.protoc.Quaternion\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"#\n\x04Time\x12\x0c\n\x04secs\x18\x01 \x01(\x05\x12\r\n\x05nsecs\x18\x02 \x01(\x05*n\n\x07MsgType\x12\x12\n\x0e\x64\x65\x66\x61ult_remain\x10\x00\x12\x10\n\x0c\x63urrent_pose\x10\x01\x12\x0f\n\x0blidar_vlp16\x10\x02\x12\x0c\n\x08\x63\x61mera_0\x10\x03\x12\x10\n\x0cvehicle_stat\x10\x04\x12\x0c\n\x08ndt_stat\x10\x05\x62\x06proto3')
)

_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='protoc.MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='default_remain', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='current_pose', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='lidar_vlp16', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='camera_0', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='vehicle_stat', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ndt_stat', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=651,
  serialized_end=761,
)
_sym_db.RegisterEnumDescriptor(_MSGTYPE)

MsgType = enum_type_wrapper.EnumTypeWrapper(_MSGTYPE)
default_remain = 0
current_pose = 1
lidar_vlp16 = 2
camera_0 = 3
vehicle_stat = 4
ndt_stat = 5



_BASEMSG = _descriptor.Descriptor(
  name='BaseMsg',
  full_name='protoc.BaseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='protoc.BaseMsg.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=72,
)


_VEHICLE_INFO = _descriptor.Descriptor(
  name='Vehicle_Info',
  full_name='protoc.Vehicle_Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vin', full_name='protoc.Vehicle_Info.vin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='protoc.Vehicle_Info.state', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=116,
)


_CURRENTPOSE = _descriptor.Descriptor(
  name='CurrentPose',
  full_name='protoc.CurrentPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='protoc.CurrentPose.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='protoc.CurrentPose.msg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='protoc.CurrentPose.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=236,
)


_LIDARVLP16 = _descriptor.Descriptor(
  name='LidarVLP16',
  full_name='protoc.LidarVLP16',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='protoc.LidarVLP16.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=285,
)


_POSESTAMPED = _descriptor.Descriptor(
  name='PoseStamped',
  full_name='protoc.PoseStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='protoc.PoseStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='protoc.PoseStamped.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=360,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='protoc.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='protoc.Header.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='protoc.Header.stamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='protoc.Header.frame_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=430,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='protoc.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='protoc.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='protoc.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=512,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='protoc.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='protoc.Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='protoc.Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='protoc.Point.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=554,
)


_QUATERNION = _descriptor.Descriptor(
  name='Quaternion',
  full_name='protoc.Quaternion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='protoc.Quaternion.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='protoc.Quaternion.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='protoc.Quaternion.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='protoc.Quaternion.w', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=612,
)


_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='protoc.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secs', full_name='protoc.Time.secs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nsecs', full_name='protoc.Time.nsecs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=649,
)

_BASEMSG.fields_by_name['msg_type'].enum_type = _MSGTYPE
_CURRENTPOSE.fields_by_name['msg_type'].enum_type = _MSGTYPE
_CURRENTPOSE.fields_by_name['msg'].message_type = _POSESTAMPED
_CURRENTPOSE.fields_by_name['info'].message_type = _VEHICLE_INFO
_LIDARVLP16.fields_by_name['msg_type'].enum_type = _MSGTYPE
_POSESTAMPED.fields_by_name['header'].message_type = _HEADER
_POSESTAMPED.fields_by_name['pose'].message_type = _POSE
_HEADER.fields_by_name['stamp'].message_type = _TIME
_POSE.fields_by_name['position'].message_type = _POINT
_POSE.fields_by_name['orientation'].message_type = _QUATERNION
DESCRIPTOR.message_types_by_name['BaseMsg'] = _BASEMSG
DESCRIPTOR.message_types_by_name['Vehicle_Info'] = _VEHICLE_INFO
DESCRIPTOR.message_types_by_name['CurrentPose'] = _CURRENTPOSE
DESCRIPTOR.message_types_by_name['LidarVLP16'] = _LIDARVLP16
DESCRIPTOR.message_types_by_name['PoseStamped'] = _POSESTAMPED
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Quaternion'] = _QUATERNION
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.enum_types_by_name['MsgType'] = _MSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseMsg = _reflection.GeneratedProtocolMessageType('BaseMsg', (_message.Message,), dict(
  DESCRIPTOR = _BASEMSG,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.BaseMsg)
  ))
_sym_db.RegisterMessage(BaseMsg)

Vehicle_Info = _reflection.GeneratedProtocolMessageType('Vehicle_Info', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLE_INFO,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Vehicle_Info)
  ))
_sym_db.RegisterMessage(Vehicle_Info)

CurrentPose = _reflection.GeneratedProtocolMessageType('CurrentPose', (_message.Message,), dict(
  DESCRIPTOR = _CURRENTPOSE,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.CurrentPose)
  ))
_sym_db.RegisterMessage(CurrentPose)

LidarVLP16 = _reflection.GeneratedProtocolMessageType('LidarVLP16', (_message.Message,), dict(
  DESCRIPTOR = _LIDARVLP16,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.LidarVLP16)
  ))
_sym_db.RegisterMessage(LidarVLP16)

PoseStamped = _reflection.GeneratedProtocolMessageType('PoseStamped', (_message.Message,), dict(
  DESCRIPTOR = _POSESTAMPED,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.PoseStamped)
  ))
_sym_db.RegisterMessage(PoseStamped)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Header)
  ))
_sym_db.RegisterMessage(Header)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Pose)
  ))
_sym_db.RegisterMessage(Pose)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Point)
  ))
_sym_db.RegisterMessage(Point)

Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNION,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Quaternion)
  ))
_sym_db.RegisterMessage(Quaternion)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), dict(
  DESCRIPTOR = _TIME,
  __module__ = 'protoc_msg_pb2'
  # @@protoc_insertion_point(class_scope:protoc.Time)
  ))
_sym_db.RegisterMessage(Time)


# @@protoc_insertion_point(module_scope)
